### ISSUE TITLE
建议增加更新日志

### ISSUE THREAD

**Issue by guenislee** [AdUhTkJm/AdUhTkJm.github.io#1]
哈喽，体验了一下这款游戏，到目前为止玩了两个小时，感觉很不错~！看到你一个小时前更新了导入导出功能，如果有更新日志就好啦

**Comment by guenislee** [comment]
另外刷新了一下之后，发现所有建筑都不需要材料就可以建造了……

**Comment by AdUhTkJm** [comment]
之前直接在master上上传了我以为没有问题的版本，结果出问题了，现在应该修复了

**Comment by AdUhTkJm** [comment]
更新日志会增加的！
